### ISSUE TITLE
Add ** foundry POW operator.

### ISSUE THREAD

**Issue by DomRe** [ncalc/ncalc-async#10]
Since ^ is being used for bitwise instead of or it would be good to get ** supported as pow instead of only having a function.

**Comment by petli** [comment]
See #11 for a PR adding this.

**Comment by petli** [comment]
Released, please give it a try @DomRe!

https://github.com/ncalc/ncalc-async/releases/tag/v3.0.4
https://www.nuget.org/packages/NCalcAsync/3.0.4

**Comment by DomRe** [comment]
Thanks @petli for this. Really appreciate it.
