### ISSUE TITLE
Question on Invariant Case String Comparasion

### ISSUE THREAD

**Issue by gumbarros** [ncalc/ncalc-async#24]
Hey! First of all congrats on the project!

I'm planning to use use it at [JJMasterData](https://www.github.com/JJConsulting/JJMasterData). 

Currently we compile expressions using `DataTable.Compute`, but I would like to migrate to NCalc.

To migrate without breaking changes, imagine the following expression:

```
'List' = 'LIST'
```

`DataTable.Compute` returns `true`, but NCalc returns `false`. Is there a way to do invariant case String Comparasion?

**Comment by yallie** [comment]
Hi @gumbarros,

sorry for my late reply!
I don't think there is a built-in support for different string comparers in NCalc.
You'll probably need to implement a custom evaluation visitor to handle invariant case.

Evaluation visitor is a class that overrides certain portions of expression evaluator logic.
Here is the example: https://dotnetfiddle.net/oydjKt

Let me know if you need help implementing it.

Or, alternatively, if you add support to string comparers in the engine, I'll be glad to accept a PR.
The API should look something like `expr.StringComparer = StringComparer.OrdinalIgnoreCase`.

Cheers!
