### ISSUE TITLE
EvaluateOptions.DecimalAsDefault support in NcalcAsync

### ISSUE THREAD

**Issue by lexalambada** [ncalc/ncalc-async#27]
Hello everyone.

I have one small question. Do you plan to add a support for EvaluateOptions.DecimalAsDefault option for Expresssion in NcalcAsync?
It would be very helpfull for high precision calculations.

**Comment by gumbarros** [comment]
Hello @lexalambada.

This probably would be solved with [this issue ](https://github.com/ncalc/ncalc/issues/172).

The logic to parse decimals is not related to `async` and should be re-used at a shared assembly in my opinion.
