### ISSUE TITLE
.netstandard

### ISSUE THREAD

**Issue by Gillardo** [ncalc/ncalc-async#3]
Does this work with dotnet core 3+?

**Comment by yallie** [comment]
Yes, it should work on dotnet core 3+.

**Comment by Gillardo** [comment]
Thanks for the reply. Last question can you override the operators? I need to be able to check if when you are adding two values that neither is null and if so, return null. Same with subtraction, multiplication and division

**Comment by yallie** [comment]
>Last question can you override the operators?

I think that's possible, but not very easy.

As far as I understand, you'll need to subclass [`EvaluationVisitor`](https://github.com/ncalc/ncalc-async/blob/master/src/NCalcAsync/Domain/EvaluationVisitor.cs) and override [`VisitAsync`](https://github.com/ncalc/ncalc-async/blob/master/src/NCalcAsync/Domain/EvaluationVisitor.cs#L100) method 
for `BinaryExpression`. Then you can use your custom visitor to evaluate an expression, 
like it's done in [`Expression.EvaluateAsync`](https://github.com/ncalc/ncalc-async/blob/master/src/NCalcAsync/Expression.cs#L212):

```c#
public async Task<object> EvaluateAsync(...)
{
	if (HasErrors()) // compiles an expression
	{
		throw new EvaluationException(Error);
	}

    // use your custom evaluation visitor that overrides standard operators
	var visitor = new CustomEvaluationVisitor(Options, evaluateParameterAsync, evaluateFunctionAsync)
	{
		Parameters = Parameters
	};

    // ...skipped for brevity...

    await ParsedExpression.AcceptAsync(visitor);
    return visitor.Result;
}
```

`Expression` always uses standard `EvaluationVisitor` and can't use custom evaluator.
So you'll end up with a custom helper class to host your own `EvaluateAsync` method.
