### ISSUE TITLE
Incorrect calculation

### ISSUE THREAD

**Issue by theadin** [ncalc/ncalc-async#4]
Hi,

When sending the formula **(1604326026000-1604325747000)/60000** NCalc returns **4.369067** but the correct result is **4.65**

`Expression e = new Expression("(1604326026000-1604325747000)/60000");`
`var evalutedResult = await e.EvaluateAsync();`

Any ideas why this might be happening?

Cheers,
Adin

**Comment by petli** [comment]
Thanks, that was a good find!  Turns out NCalc have always forced long integers to be single-precision floats, which caused loss of precision. I've published v2.0.2 at Nuget now that fixes this: https://www.nuget.org/packages/NCalcAsync/2.0.2

**Comment by petli** [comment]
I'm preparing a fix for ncalc-sync too.

**Comment by theadin** [comment]
Wow. Thanks for the quick fix!.

I've been using ncalc-sync since you created it I believe. So your work is being put to good use.

Much appreciated.
Adin

**Comment by theadin** [comment]
I upgraded to 2.0.2 and can confirm the issue is fixed.
